
const SET_COUNTRIES = 'SET_COUNTRIES',
    GET_COUNTRY_DETAIL = 'GET_COUNTRY_DETAIL',
    ORDER_COUNTRIES_ASC = 'ORDER_COUNTRIES_ASC',
    ORDER_COUNTRIES_DESC = 'ORDER_COUNTRIES_DESC',
    ASC_BY_POB = 'ASC_BY_POB',
    DESC_BY_POB = 'DESC_BY_POB',
    FILTER_CONTINENT = 'FILTER_CONTINENT',
    FILTER_ACTIVITY = 'FILTER_ACTIVITY'

export { SET_COUNTRIES, GET_COUNTRY_DETAIL, ORDER_COUNTRIES_ASC, ASC_BY_POB, ORDER_COUNTRIES_DESC, DESC_BY_POB, FILTER_CONTINENT, FILTER_ACTIVITY }
