
const SET_COUNTRIES = 'SET_COUNTRIES',
    SET_COUNTRY_DETAIL = 'SET_COUNTRY_DETAIL',
    ORDER_COUNTRIES_ASC = 'ORDER_COUNTRIES_ASC',
    ORDER_COUNTRIES_DESC = 'ORDER_COUNTRIES_DESC',
    GET_COUNTRY_BY_NAME = 'GET_COUNTRY_BY_NAME',

    ASC_BY_POB = 'ASC_BY_POB',
    DESC_BY_POB = 'DESC_BY_POB',

    FILTER_CONTINENT = 'FILTER_CONTINENT',
    FILTER_ACTIVITY = 'FILTER_ACTIVITY',

    SET_PAGES = 'SET_PAGES',
    IS_LOADING = 'IS_LOADING'

export { SET_COUNTRIES, SET_COUNTRY_DETAIL, ORDER_COUNTRIES_ASC, ASC_BY_POB, ORDER_COUNTRIES_DESC, DESC_BY_POB, FILTER_CONTINENT, FILTER_ACTIVITY, GET_COUNTRY_BY_NAME, SET_PAGES, IS_LOADING }
